//Types for Auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//Types for Company
export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS';
export const ADD_COMPANY_DETAILS = 'ADD_COMPANY_DETAILS';
export const UPDATE_COMPANY_DETAILS = 'UPDATE_COMPANY_DETAILS';
export const DATA_LOADING = 'DATA_LOADING';

export const GET_JOBPOSTINGS = 'GET_JOBPOSTINGS';
export const ADD_JOBPOSTINGS = 'ADD_JOBPOSTINGS';
export const UPDATE_JOBPOSTINGS = 'UPDATE_JOBPOSTINGS';
export const DELETE_JOBPOSTINGS = 'DELETE_JOBPOSTINGS';

export const MAKE_SHORTLISTED = 'MAKE_SHORTLISTED';


//Types for Company User
export const GET_COMPANY_USER_DETAILS = 'GET_COMPANY_USER_DETAILS';
export const UPDATE_COMPANY_USER_DETAILS = 'UPDATE_COMPANY_USER_DETAILS';
export const COMPANY_USER_DATA_LOADING = 'COMPANY_USER_DATA_LOADING';
export const SET_COMPANY_PROFILE_COMPLETE_STATUS = 'SET_COMPANY_PROFILE_COMPLETE_STATUS';
export const SET_OWN_PROFILE_COMPLETE_STATUS = 'SET_OWN_PROFILE_COMPLETE_STATUS';

//Types for Students
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';